export enum Permission {
    EDIT_WORKFLOW = <any>'EDIT_WORKFLOW',
    DELETE_REQUEST = <any>'DELETE_REQUEST',
    APPROVE_CIVILIAN = <any>'APPROVE_CIVILIAN',
    APPROVE_SOLDIER = <any>'APPROVE_SOLDIER',
    APPROVE_CAR = <any>'APPROVE_CAR',
    EDIT_USER_PERMISSIONS = <any>'EDIT_USER_PERMISSIONS'
}

